### ISSUE TITLE
A Question About Moving

### ISSUE THREAD

**Issue by PashPaw** [PDP-6/JOSS-II#59]
@larsbrinkhoff So, should this also be moved to the PDP-6 org?  I honestly feel that it fits more there than here on the PDP-10 org but I would like some feedback.

**Comment by larsbrinkhoff** [comment]
Yes, I do think the PDP-6 organization would be better now that it's seeing some use.

**Comment by PashPaw** [comment]
Same.  And done.  Thanks.
